template: |
  ## Changes
  $CHANGES
change-template: '- **$TITLE** (#$NUMBER)'

version-template: "$MAJOR.$MINOR.$PATCH"
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

categories:
  - title: 'New Features'
    labels:
      - 'main'
      - 'major'
      - 'feature'
      - 'common'
      - 'minor'
  - title: 'Build and refactoring'
    labels:
      - 'build'
      - 'refactoring'
  - title: 'Hot Fixes'
    labels:
      - 'hotfix'
  - title: 'Bugs Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: 'Patches'
    labels:
      - 'patch'
  - title: 'Documentation'
    labels:
      - 'config'
      - 'documentation'
      - 'docs'
  - title: 'Configuration'
    labels:
      - 'dependencies'
  - title: 'Tests'
    labels:
      - 'test'
  - title: 'Maintenance'
    labels:
      - 'automatization'
      - 'code'
      - 'work'
      - 'enhancement'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - main
      - build
      - refactoring
      - major
  minor:
    labels:
      - dependencies
      - feature
      - common
      - minor
  patch:
    labels:
      - automatization
      - code
      - work
      - enhancement
      - bug
      - fix
      - patch
      - config
      - documentation
      - docs
      - bugfix
      - hotfix
      - test
  default: patch
