name: CODECOV
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
      - name: Test Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
