name: CODECOV

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install pytest
        pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: python -m pytest test --junit-xml pytest.xml
    - name: Test Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV }}
