name: Deploy_2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on ssh server
    steps:
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
