name: Deploy_2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on ssh server
    steps:
      - uses: actions/checkout@v2
      
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: src/
          remote_path: ${{ secrets.TARGET }}
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
