name: Verify type labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
      - name: Verify type labels
        uses: zwaldowski/match-label-action@v2
        with:
          allowed: 'config, documentation, feature, fix, hotfix, test'
